baseURL = "https://lulullia.github.io/"
theme = "tailwind"

title = "Purple Planetarium"
author = "Lulullia"
copyright = "Lulullia"

languageCode = "en"
#defaultContentLanguage = "en"
#defaultContentLanguageInSubdir = true

refLinksErrorLevel = "WARNING"
refLinksNotFoundURL = '#'

paginate = 10

# MENU
[menu]

  [[menu.main]]
    identifier = "about"
    name = "About"
    pageRef = "/about"
    weight = 10

  [[menu.main]]
    identifier = "projects"
    name = "Projects"
    pageRef = "/projects"
    weight = 20

  [[menu.main]]
    identifier = "blog"
    name = "Blog"
    pageRef = "/blog"
    weight = 0


# MODULE
[module]

  [[module.mounts]]
      source = "content"
      target = "content"
  [[module.mounts]]
      source = "D:/Files/!!NOTES!!/Chaotic Creativity/Moons/Blog"
      target = "content"


# TAXONOMIES
[taxonomies]
  category = "categories"
  tag = "tags"
  series = "series"
