baseURL = "https://lulullia.github.io/"
theme = "stack"

title = "Purple Planetarium"
author = "Lulullia"
copyright = "Lulullia"

refLinksErrorLevel = "WARNING"
refLinksNotFoundURL = "#"

paginate = 10

# LANGUAGE
defaultContentLanguage = "en"

[languages]

  [languages.en]
    #contentDir = "content/en"
    disabled = false
    languageCode = "en"
    languageDirection = "ltr"
    languageName = "English"
    params.sidebar.subtitle = "One world, countless stories"

  [languages.fr]
    #contentDir = "content/en"
    disabled = false
    languageCode = "fr"
    languageDirection = "ltr"
    languageName = "Français"
    params.sidebar.subtitle = "Un monde, d'innombrables histoires"

# MODULE
[module]

  [[module.mounts]]
      source = "content"
      target = "content"
  [[module.mounts]]
      source = "D:/Files/!!NOTES!!/Chaotic Creativity/Moons/Blog"
      target = "content"

  [[module.mounts]]
      source = "assets"
      target = "assets"
  [[module.mounts]]
      source = "D:/Files/!!NOTES!!/Chaotic Creativity/Storehouse/att/img"
      target = "assets/img"


# PERMALINKS
[permalinks]
  page = "/:slug/"

  blog = "/entry/:slug/"
  artblog = "/entry/:slug/"

  world = "/world/:slug/"
  categories = "/world/:slug/"


# TAXONOMIES
[taxonomies]
  category = "categories"
  project = "projects"
  topic = "topics"
