# STACK PARAMS #
# SETTINGS
mainSections = ["blog", "artblog"]
featuredImageField = "banner"

# WIDGETS
[widgets]

  [[widgets.homepage]]
    type = "search"
  [[widgets.homepage]]
    type = "categories"
  [[widgets.homepage]]
    type = "newsletter-sidebar"
  [[widgets.homepage]]
    type = "kofi-button"

  [[widgets.page]]
    type = "search"
  [[widgets.page]]
    type = "toc"
  [[widgets.page]]
    type = "newsletter-sidebar"
  [[widgets.page]]
    type = "kofi-button"
